domain_name: local.com

# Default apache host and ports
default_apache_port_http: 80
default_apache_port_https: 443
default_apache_host: "localhost"
default_apache_server_aliases: []
default_email: "admin@localhost"

apache_user: "www-user"
apache_group: "www-user"

vhost_sites:
- {
    host: 'owncloud',
    webfolder: '',
    user: '{{ apache_user }}',
    group: '{{ apache_group }}',
    listen_port: '{{ apache_http_port | default(default_apache_port_http) }}',
    https_port: '{{ apache_https_port | default(default_apache_port_https) }}',
    admin_email: '{{ apache_admin_email | default(default_email) }}',
    aliases: ['owncloud.{{ domain_name }}'],
    allowoverride: "None",
    options: "FollowSymLinks"
  }

https_vhost_sites:
- {
    host: 'owncloud',
    webfolder: '',
    user: '{{ apache_user }}',
    group: '{{ apache_group }}',
    listen_port: '{{ apache_https_port | default(default_apache_port_https) }}',
    admin_email: '{{ apache_admin_email | default(default_email) }}',
    aliases: ['owncloud.{{ domain_name }}'],
    allowoverride: "None",
    options: "FollowSymLinks"
  }

owncloud_db_name: "owncloud_db"
owncloud_db_user: "owncloud_user"
owncloud_db_password: "@TODO: yourpw"

postgresql_databases:
 - name: "www-db"
   template: "template0"
 - name: "{{ owncloud_db_name }}"
   template: "template0"

# List of users to be created
postgresql_users:
  - username: www-user
    password: www-user
    encrypted: "no"
  - username: "{{ owncloud_db_user }}"
    password: "{{ owncloud_db_password }}"
    encrypted: "no"


# List of user privileges to be applied
postgresql_user_privileges:
  - name: www-user
    db: www-db
    priv: "ALL"
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"
  - name: "{{ owncloud_db_user }}"
    db: "{{ owncloud_db_name }}"
    priv: "ALL"
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"
