- name: Owncloud | copy config
  template:
    src: config.php.j2
    dest: /var/www/owncloud/config/config.php

- name: Owncloud | chown owncloud directory
  command: chdir=/var/www chown -R {{ apache_user }}:{{ apache_group }} owncloud


- name: Owncloud | create log directory
  file: dest=/var/log/owncloud state=directory owner={{ apache_user }}

