
- name: chown owncloud directory
  command: chdir=/var/www chown -R {{ apache_user }}:{{ apache_group }} owncloud

- name: create log directory
  file: dest=/var/log/owncloud state=directory owner={{ apache_user }}
