
- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: PostgreSQL | create database users
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    encrypted: "{{ item.encrypted }}"
    state: "present"
  with_items: postgresql_users
  when: postgresql_users|length > 0

- name: PostgreSQL | Update the user privileges
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
    priv: "{{ item.priv | default('ALL') }}"
    state: present
  with_items: postgresql_user_privileges
  when: postgresql_user_privileges|length > 0

- name: PostgreSQL | Check unnecessary privileges
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    name: "{{ item.name }}"
    role_attr_flags: "{{ item.role_attr_flags | default('NOSUPERUSER,NOCREATEDB') }}"
  with_items: postgresql_user_privileges
  when: postgresql_user_privileges|length > 0